email:
  basic_config: &basic_config
    - to: an.xiaokang@jenkins-zh.cn
      cc: an.xiaokang@jenkins-zh.cn
      replyTo: an.xiaokang@jenkins-zh.cn
      body: "this is a message from jenkins-zh"
  success:
    <<: *basic_config
    subject: "nginx was reloaded"
  failed:
    <<: *basic_config
    subject: "failed to reload nginx"
git:
  url: "git@github.com:jenkins-zh/application-operation.git"
  credentials_id:
  folders:
    - config/nginx

image: "nginx:1.17.9-alpine"
nginx_config: "application-operation/config/nginx/nginx.conf"
