version: "3.7"
services:
  jenkins-wechat:
    image: docker.io/surenpi/jenkins-wechat:aaa2fb4
    container_name: jenkins-wechat
    restart: on-failure
    expose:
      - "18080"
    volumes:
      - "/var/wechat/config:/config"
    networks:
      - apps
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
networks:
  apps: