version: "3.7"
services:
  jenkins-nginx:
    image: nginx:1.17.9-alpine
    container_name: jenkins-nginx
    command: ["nginx", "-g", "'daemon off;'"]
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - "/etc/nginx/nginx.current.conf:/etc/nginx/nginx.conf"
    networks:
      - apps
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
networks:
  apps: