node:
  ucloud
git:
  url: "https://github.com/jenkins-zh/application-operation.git"
  branch: master
  folders:
    - compose
    - config/nginx

nginx_config: nginx/nginx.current.conf
compose_file: compose/docker-compose.yaml

email:
  basic_config: &basic_config
    - to: an.xiaokang@jenkins-zh.cn
      cc: ops@jenkins-zh.cn
      replyTo: an.xiaokang@jenkins-zh.cn
      body: "This message was from jenkins-zh."
  success:
    <<: *basic_config
    subject: "apps was updated"
  failed:
    <<: *basic_config
    subject: "failed to update apps"
