git:
  url: "https://github.com/anxk/application-operation.git"
  branch: "anxk0411"
  folders: 
    - "config/ssh"
    - "apps/ssh-key-killer"

config_file: "application-operation/config/ssh"

node: ucloud